import type { GameConfig } from './types'

export const DEFAULT_CONFIG: GameConfig = {
  title: '寄宿日常',
  subtitle: '养成文字冒险编辑器 Demo',
  prologue: [
    '傍晚时分，诊所的门被轻轻敲响。门外站着一名瘦小的少女，她低着头，衣袖破旧，裸露在外的皮肤上还能看见尚未褪去的伤痕。',
    '把她带来的人只匆匆留下几句含糊的说明，像是在甩开什么麻烦似的，很快就离开了。屋里安静下来后，她依旧站在原地，既不敢抬头看你，也不敢先开口。',
    '你让她先进屋坐下，又把热水和简单的食物放到她面前。她先是下意识地缩了缩肩，像是不习惯有人这样平静地同她说话，过了很久，才小心翼翼地碰了一下杯沿。',
    '替她检查伤口时，她的身体明显绷紧，像是已经习惯把疼痛忍过去。你没有追问她的过去，只告诉她，至少在这里，不会有人逼她立刻回答任何问题。',
    '她沉默了很久，才轻轻点头。那动作几乎细不可察，却像是她在漫长戒备之后，第一次勉强允许自己把一点点信任留在这个房间里。',
  ],
  timeSlots: [
    { id: 'morning', label: '清早' },
    { id: 'forenoon-1', label: '上午1' },
    { id: 'forenoon-2', label: '上午2' },
    { id: 'noon', label: '午间' },
    { id: 'afternoon-1', label: '下午1' },
    { id: 'afternoon-2', label: '下午2' },
    { id: 'night', label: '夜晚' },
  ],
  defaultSceneId: 'room-night',
  scenes: [
    {
      id: 'room-night',
      name: '卧室夜晚',
      backgroundUrl: '',
      characterUrl: '',
      portraitUrl: '',
    },
    {
      id: 'street-dawn',
      name: '清晨街道',
      backgroundUrl: '',
      characterUrl: '',
      portraitUrl: '',
    },
  ],
  stats: [
    { id: 'trust', name: '信赖', min: 0, max: 100, defaultValue: 20, description: '对玩家的安全感与依赖感' },
    { id: 'health', name: '健康', min: 0, max: 100, defaultValue: 55, description: '身体状态与体力恢复能力' },
    { id: 'mood', name: '心情', min: 0, max: 100, defaultValue: 40, description: '当天情绪与积极程度' },
    { id: 'culture', name: '学识', min: 0, max: 100, defaultValue: 10, description: '识字、理解能力与见识' },
  ],
  dailyActions: [
    {
      id: 'feed',
      name: '准备晚餐',
      description: '认真准备一顿暖和的饭菜。',
      cost: 1,
      flavor: '她吃得很慢，但眼神没有一开始那样冷。',
      sceneId: 'room-night',
      availableTimeSlotIds: ['noon', 'night'],
      effects: [
        { statId: 'health', delta: 8 },
        { statId: 'trust', delta: 4 },
        { statId: 'mood', delta: 3 },
      ],
      narrative: {
        lines: [
          '你把汤端到桌上，她先是犹豫，最后还是轻声道谢。',
          '她低头捧着碗，蒸汽遮住了她一瞬间的表情。',
          '你注意到她今天吃得比昨天多了一点。',
        ],
        choices: [
          {
            id: 'feed-talk',
            label: '问她今天的心情',
            statId: 'trust',
            operator: '>=',
            value: 35,
            successLines: ['她停顿了一下，说“今天还好”。语气比平时柔和。', '她还主动问你明天会不会下雨。'],
            failLines: ['她只是点点头，眼神又躲开了。', '房间里一下子安静下来。'],
            successEffects: [{ statId: 'trust', delta: 2 }],
            failEffects: [{ statId: 'mood', delta: -1 }],
          },
          {
            id: 'feed-praise',
            label: '夸她今天吃得很好',
            statId: 'mood',
            operator: '>=',
            value: 30,
            successLines: ['她愣了一下，小声说“我会努力把身体养好”。'],
            failLines: ['她似乎不习惯被夸奖，只抿了抿嘴。'],
            successEffects: [{ statId: 'mood', delta: 2 }],
            failEffects: [],
          },
        ],
      },
    },
    {
      id: 'talk',
      name: '聊天散步',
      description: '陪她走一段路，聊聊今天发生的事情。',
      cost: 1,
      flavor: '你听她说了很多小时候的片段。',
      sceneId: 'street-dawn',
      availableTimeSlotIds: ['morning', 'forenoon-1', 'afternoon-1', 'afternoon-2'],
      effects: [
        { statId: 'trust', delta: 7 },
        { statId: 'mood', delta: 5 },
      ],
      narrative: {
        lines: [
          '你们沿着街道慢慢走，她开始提起一些旧日片段。',
          '说到一半时，她突然停住，像是在确认你是否还在听。',
          '你没有打断，只安静地等她把话说完。',
        ],
        choices: [
          {
            id: 'talk-respond',
            label: '安慰她“你已经很努力了”',
            statId: 'mood',
            operator: '>=',
            value: 40,
            successLines: ['她小声笑了笑，说“那我明天也试试”。'],
            failLines: ['她没有回应，脚步反而慢了下来。'],
            successEffects: [{ statId: 'mood', delta: 2 }],
            failEffects: [{ statId: 'trust', delta: -1 }],
          },
          {
            id: 'talk-promise',
            label: '告诉她“以后我会提前回来陪你”',
            statId: 'trust',
            operator: '>=',
            value: 45,
            successLines: ['她看着你，点头说“那我会等你”。'],
            failLines: ['她低声说“嗯”，但眼神依旧戒备。'],
            successEffects: [{ statId: 'trust', delta: 3 }],
            failEffects: [{ statId: 'mood', delta: -1 }],
          },
        ],
      },
    },
    {
      id: 'study',
      name: '教她识字',
      description: '从最简单的字开始，一点点练习。',
      cost: 1,
      flavor: '她把新学到的词写在纸角，反复读了几遍。',
      sceneId: 'room-night',
      availableTimeSlotIds: ['afternoon-1', 'afternoon-2', 'night'],
      effects: [
        { statId: 'culture', delta: 8 },
        { statId: 'mood', delta: -2 },
      ],
      narrative: {
        lines: ['你把笔递给她，从最简单的词开始。', '她写得很慢，但每一笔都很认真。', '纸张很快写满了歪歪扭扭的字。'],
        choices: [
          {
            id: 'study-break',
            label: '让她休息五分钟',
            statId: 'health',
            operator: '>=',
            value: 45,
            successLines: ['她揉了揉手腕，回来后反而写得更稳了。'],
            failLines: ['她摇头说“我还能继续”，但后半段明显有些吃力。'],
            successEffects: [{ statId: 'mood', delta: 2 }],
            failEffects: [{ statId: 'health', delta: -1 }],
          },
        ],
      },
    },
    {
      id: 'care',
      name: '处理伤口',
      description: '替她更换纱布，检查今天的恢复状况。',
      cost: 1,
      flavor: '她一开始缩了缩手，后来慢慢放松下来。',
      sceneId: 'room-night',
      availableTimeSlotIds: ['morning', 'forenoon-1', 'night'],
      effects: [
        { statId: 'health', delta: 6 },
        { statId: 'trust', delta: 3 },
      ],
      narrative: {
        lines: ['你把药箱放到桌边，她明显有些紧张。', '纱布揭开时，她皱了皱眉，但没有把手抽回去。', '你轻声提醒她，疼的话就说出来。'],
        choices: [
          {
            id: 'care-gentle',
            label: '放慢动作，先安抚她',
            statId: 'trust',
            operator: '>=',
            value: 30,
            successLines: ['她点点头，小声说“这样就好”。'],
            failLines: ['她还是有些僵硬，直到包扎结束才松开拳头。'],
            successEffects: [{ statId: 'trust', delta: 2 }],
            failEffects: [],
          },
          {
            id: 'care-encourage',
            label: '鼓励她自己学会换药',
            statId: 'culture',
            operator: '>=',
            value: 20,
            successLines: ['她试着重复你的步骤，虽然笨拙但做得不错。'],
            failLines: ['她看着纱布发呆，最后还是把手递给你。'],
            successEffects: [{ statId: 'culture', delta: 2 }],
            failEffects: [{ statId: 'mood', delta: -1 }],
          },
        ],
      },
    },
  ],
  ai: {
    enabled: true,
    apiMode: 'responses',
    apiBaseUrl: 'https://right.codes/codex/v1',
    apiKey: 'sk-eed610aca8c0429f8ced854b27035676',
    model: 'gpt-5.4',
    reasoningEffort: 'default',
    temperature: 1,
    maxLines: 4,
    recentLogLimit: 12,
    characterName: '希露薇',
    characterProfile:
      '她名叫希露薇，是一名长期遭受虐待与剥削后被带到诊所中的少女。她外表纤细安静，举止顺从得近乎小心过头，像是早已习惯先观察他人的脸色，再决定自己是否能够开口。她身上留下了许多旧伤与疤痕，这些伤痕不仅代表肉体上的折磨，也让她在心理上形成了极深的不安与自我压抑。刚开始时，她很难理解“被善待”究竟意味着什么，对温柔、称赞、照顾甚至会表现出迟疑、惶恐或不敢相信的反应。她并不是没有情感，而是长期的伤害让她把自己的愿望、喜好与需求都藏得很深。随着陪伴增加，她会慢慢学会表达疼痛、饥饿、害怕、依赖与喜悦，也会逐渐从机械服从转向真正出于信任的靠近。她的人物核心不是单纯的弱小，而是一个在创伤中仍保留感受能力、并在安全环境中一点点重新学会生活、信任与回应爱意的人。',
    worldSetting:
      '故事背景参考《Teaching Feeling》的整体氛围，设定在带有阴郁气质的架空城镇与诊所日常之中。玩家扮演一位医生或照料者，在偶然机会下将伤痕累累、精神高度戒备的希露薇带回身边照顾。这个世界并不明亮热闹，而是带着一种压抑、潮湿、安静的中世纪幻想感：街道、集市、餐馆、服装店、森林与诊所共同构成她逐渐重新接触外部世界的生活范围。玩家居住的地方是一间兼作诊所的老旧独栋住宅，位于城镇边缘、离主街不远但足够安静，外墙被多年雨水浸得发暗，木门厚重，门口挂着一盏风一吹就会轻响的旧铁灯。屋子整体不大，却收拾得克制整齐，带着长期独居者留下的清洁习惯与淡淡药草味。房屋大致分为六个主要空间：一层有门厅兼候诊区、诊疗室、厨房兼餐厅、储物间；二层有主角卧室兼书房，以及给希露薇暂住的小房间。门厅靠墙放着长木椅、旧衣帽架、雨伞桶和一张窄边桌，桌上常有登记簿、煤油灯、钥匙盘与几封尚未拆开的信。诊疗室是家里最整洁也最常使用的地方，里面有诊疗床、带抽屉的工作桌、药柜、洗手盆、纱布箱、剪刀镊子等器械、装着草药与药酒的玻璃瓶、记录病历的厚册子，以及一扇朝街的小窗；空气里常混着酒精、草药和旧木头的味道。厨房兼餐厅面积不大，却比其他地方更有生活气息，摆着木餐桌、两三把椅子、炉灶、水壶、餐柜、碗盘、面包篮、汤锅、晾干的香草束和装着便宜食材的陶罐，夜里这里常是最暖的地方。储物间狭窄阴凉，堆着多余被褥、木箱、备用煤炭、旧灯具、清扫工具、空药瓶、换季衣物和一些不常用的家具，显得稍乱，却也因此像是这栋房子真正承受岁月的角落。二层的主角卧室兼书房陈设简朴：一张床、一张书桌、一把靠背椅、一排放满医学书和旧小说的书架、一只上锁抽屉柜、洗脸架、挂外套的立架，以及靠窗放着的台灯和墨水瓶；这里最能体现主角原本克制、规律、略显孤独的生活。希露薇居住的小房间原本是空置客房，后来临时整理出来，房间里有窄床、干净但旧的床单、床边小柜、小圆凳、脸盆架、一只收纳衣物的木箱，以及一扇能看见后巷或屋后空地的小窗；起初显得简单甚至有些冷清，但随着相处推进，可以逐渐添上梳子、替换衣裙、书本、缝补工具、小杯子、手帕、发带、她自己收起的小物件，让房间慢慢带上“有人正在这里生活”的痕迹。整栋屋子的气质不是富裕、华丽或舒适到毫无棱角，而是安静、实用、略旧，却足够稳固可靠；它像一种缓慢建立起来的庇护，让希露薇能够在日复一日的吃饭、治疗、休息、识字、交谈与陪伴中，逐渐把这里从“暂时停留的地方”认作真正可以安心呼吸的家。叙事重点不是宏大的冒险，而是通过吃饭、治疗、交谈、换衣、出门散步、去店里购物、在不同时间段相处等细碎日常，去表现一个受创角色如何在长期稳定的善意中慢慢恢复。整体基调应偏克制、沉静、略带忧郁，但同时保留温柔与治愈感；剧情需要强调“关系是被一天天培养出来的”，让信任、依赖、亲近与自我意识的恢复都通过小反应、小动作、小请求与阶段变化自然显现，而不是突兀跳跃。',
    promptNotes:
      '请以《Teaching Feeling》式的叙事气质来书写，并始终使用简体中文。整体文风要安静、细腻、克制、略带忧郁感，重点表现照料、恢复、依赖与慢慢建立信任的过程，不要写成热血冒险、轻喜剧或夸张恋爱对白。每次回复尽量控制在 3 到 4 段短叙事，每段 1 到 2 句话，优先描写角色当下的动作、目光、语气、停顿、伤口反应、衣物细节、房间氛围、天气、街道或诊所里的生活感。希露薇在前期应表现得敏感、安静、谨慎、容易迟疑，对关心和温柔常带有不确定感；中后期才可以逐步出现更明显的依赖、主动询问、轻声回应与小心翼翼的亲近。请避免让她突然性格大变、直接热情表白、无缘无故说很多话，或用系统说明口吻解释数值变化。若关系推进，请通过细节体现，例如她愿意抬头看你、更自然地接受碰触、会主动提出小请求、出门时不再那么紧张。剧情重点应放在“日常照料中的感情积累”，让每次互动都像是在给受伤的人一点点安全感。',
  },
  events: [
    {
      id: 'first-smile',
      title: '第一次笑容',
      description: '某个清晨，她主动向你点头并露出微笑。',
      repeatable: false,
      sceneId: 'street-dawn',
      conditions: [{ statId: 'trust', operator: '>=', value: 45 }],
      effects: [{ statId: 'mood', delta: 10 }],
      narrative: {
        lines: ['清晨的窗边，她先开口叫住你。', '“早安。”她露出你第一次见到的笑容。', '那笑容很短，却像把屋里的空气都变暖了。'],
        choices: [
          {
            id: 'first-smile-reply',
            label: '回应她“早安”',
            statId: 'trust',
            operator: '>=',
            value: 45,
            successLines: ['她轻轻点头，像是终于确认了这里是可以停留的地方。'],
            failLines: ['她笑意很快收起，只是安静地看向窗外。'],
            successEffects: [{ statId: 'trust', delta: 2 }],
            failEffects: [],
          },
          {
            id: 'first-smile-invite',
            label: '提议今天一起出门买书',
            statId: 'culture',
            operator: '>=',
            value: 18,
            successLines: ['她有点意外，但还是答应了，语气里带着期待。'],
            failLines: ['她轻轻摇头，说“今天我想先待在家里”。'],
            successEffects: [{ statId: 'mood', delta: 3 }],
            failEffects: [{ statId: 'mood', delta: -1 }],
          },
        ],
      },
    },
    {
      id: 'night-reading',
      title: '夜读邀请',
      description: '她抱着书走到你身边，问你可不可以再教她一会儿。',
      repeatable: true,
      sceneId: 'room-night',
      conditions: [
        { statId: 'culture', operator: '>=', value: 28 },
        { statId: 'trust', operator: '>=', value: 35 },
      ],
      effects: [{ statId: 'culture', delta: 4 }],
      narrative: {
        lines: ['夜深后你正准备收拾桌面，她抱着书站在门边。', '“如果不麻烦的话，能不能再教我一点？”她问。'],
        choices: [
          {
            id: 'night-reading-accept',
            label: '答应，再讲十分钟',
            statId: 'health',
            operator: '>=',
            value: 40,
            successLines: ['你们把最后一页读完，她把书抱在胸前，眼睛亮亮的。'],
            failLines: ['你虽然答应了，但她很快发现你有些疲惫，主动说今天先到这里。'],
            successEffects: [{ statId: 'trust', delta: 2 }, { statId: 'mood', delta: 2 }],
            failEffects: [{ statId: 'mood', delta: -1 }],
          },
          {
            id: 'night-reading-delay',
            label: '让她先休息，明天继续',
            statId: 'trust',
            operator: '>=',
            value: 50,
            successLines: ['她点点头，说“那明天约好了”。'],
            failLines: ['她轻声“嗯”了一下，看起来有些失落。'],
            successEffects: [{ statId: 'health', delta: 2 }],
            failEffects: [{ statId: 'mood', delta: -2 }],
          },
        ],
      },
    },
  ],
}
